logsBucket: "gs://builds-logs-bucket"
steps:
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   args:
  #   - gcloud
  #   - functions
  #   - deploy
  #   - function-air-pollution
  #   - --entry-point=gcloud_get_openweather_data_function
  #   - --region=us-central1
  #   - --source=./gcloud/gcloud_functions
  #   - --trigger-http
  #   - --runtime=python311

  # [START composer_cicd_dagsync_yaml]

  # # Step to download the Rust installation script
  # - name: 'gcr.io/cloud-builders/curl'
  #   args: ['--proto', '=https', '--tlsv1.2', '-sSf', '-o', '/tmp/rustup.sh', 'https://sh.rustup.rs']

  # # Step to execute the Rust installation script
  # - name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args: ['/tmp/rustup.sh', '-y']
    

  # Step to install Airflow and other Python dependencies
  - name: 'python'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--user']
    

  # Run your Python script
  - name: 'python'
    entrypoint: 'python'
    args: ['gcloud/gcloud_data_pipeline/dags/upload_dags_to_composer.py', '--dags_directory=dags/', '--dags_bucket=gs://air-pollution-bucket/dags']
    