logsBucket: "gs://builds-logs-bucket"
steps:
  - name: 'deploy-cloud-functions'
    args:
      - 'functions'
      - 'deploy'
      - 'function-air-pollution'
      - '--runtime'
      - 'python311'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--source'
      - './gcloud/gcloud_functions'


  - name: 'deploy-workflows'
    args:
      - 'workflows'
      - 'deploy'
      - 'workflow-air-pollution'
      - '--source'
      - './workflow.yaml'
