logsBucket: "gs://builds-logs-bucket"
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'function-air-pollution'
      - '--runtime'
      - 'python311'
      - '--trigger-http'
      - '--trigger-event'
      - ''
      - '--allow-unauthenticated'
      - '--source'
      - './gcloud/gcloud_functions'


  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'workflows'
      - 'deploy'
      - 'workflow-air-pollution'
      - '--source'
      - './workflow.yaml'
