steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - function-air-pollution
  - --source=.
  - --runtime=python310
  - --trigger-event=https

logsBucket: "gs://builds-logs-bucket"
