logsBucket: "gs://builds-logs-bucket"
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - function-air-pollution
    - --region=us-central1
    - --source=./gcloud/gcloud_functions
    - --trigger-http
    - --runtime=python311
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'functions'
      - 'deploy'
      - 'function-air-pollution'
      - '--runtime'
      - 'python311'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--source'
      - './gcloud/gcloud_functions'


  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'workflows'
      - 'deploy'
      - 'workflow-air-pollution'
      - '--source'
      - './workflow.yaml'
