logsBucket: "gs://builds-logs-bucket"
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - function-air-pollution
    - --entry-point=gcloud_get_openweather_data_function
    - --region=us-central1
    - --source=./gcloud/gcloud_functions
    - --trigger-http
    - --runtime=python311

  # [START composer_cicd_dagsync_yaml]

  # install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # run
  - name: python
    entrypoint: python
    args: ["gcloud/gcloud_data_pipeline/dags/upload_dags_to_composer.py", "--dags_directory=dags//", "--dags_bucket=gs://air-pollution-bucket//dags"]

  # [END composer_cicd_dagsync_yaml]
