main:
  params: [input]
  steps:
    - call_function:
        call: http.get
        args:
          url: https://us-central1-useful-tempest-398111.cloudfunctions.net/function-1-examle
          auth:
            type: OIDC
        result: function_response
    - publish_to_pubsub:
        call: googleapis.pubsub.v1.projects.topics.publish
        args:
          topic: projects/useful-tempest-398111/topics/air-pollution-api
          body:
            messages:
              - data: ${base64.encode(text.encode(function_response.body))}
        result: pubsub_response
    - return_results:
        return: ${pubsub_response}